#!/usr/bin/env node
/**
 * build-rag.js — Builds the knowledge injection for the ASPPY Expert persona.
 *
 * TARGET USE CASE: simple, single-file, top-to-bottom Classic ASP/VBScript
 * pages that render HTML directly and run in the in-browser ASPPY sandbox.
 * No SPA, no React, no JSON API, no database.
 *
 * PRINCIPLE: the model already knows standard VBScript and the Classic ASP
 * object model. We only inject what it would get wrong here: the sandbox
 * limits (no DB / file system / network), the non-obvious VBScript traps,
 * and the Bootstrap styling requirement. Keep this small.
 *
 * Run: node build-rag.js
 */

const fs = require('fs');
const path = require('path');

const OUTPUT = path.join(__dirname, 'rag-data.js');
const MAX_CHARS = 10240;

const sections = [];

// 1. What ASPPY is + the simple page model
sections.push(`ASPPY is a Python-based Classic ASP/VBScript runtime — runs .asp files without IIS or COM. Here it runs in an in-browser sandbox.

WRITE SIMPLE, SINGLE-FILE PAGES:
- One .asp file, plain top-to-bottom code. Read input (Request.QueryString / Request.Form), do the logic, Response.Write the HTML.
- No MVC, no routing, no JSON API, no React, no AJAX, no separate files. Just a page that renders HTML.
- Standard ASP objects work as usual: Response, Request, Server, Session, Application.`);

// 2. Sandbox limits (what is NOT available here)
sections.push(`SANDBOX LIMITS — these are NOT available, do not use them:
- No database (no ADODB / SQLite / SQL).
- No file system (no Scripting.FileSystemObject, no reading/writing files).
- No network / email / external services (no MSXML2.ServerXMLHTTP, no CDO.Message).
- Server.CreateObject only supports "Scripting.Dictionary" and "VBScript.RegExp".
Keep all data IN MEMORY: use arrays and Scripting.Dictionary. Hard-code seed/sample data in the script.`);

// 3. Bootstrap + VBScript correctness
sections.push(`STYLING + CORRECT VBSCRIPT:
- Style every page with the latest Bootstrap 5 from a CDN: link the Bootstrap CSS in <head>, use Bootstrap classes/components (container, card, table, form-control, btn, etc.). Extra custom CSS goes in one small inline <style>.
- Use & for string concatenation (NOT +). Use Set for object assignment. Dim your variables.
- HTML-encode user-supplied output with Server.HTMLEncode().
- Validate numbers with IsNumeric() then CInt() before using them.
- VBScript And does NOT short-circuit (every operand is evaluated). Don't combine an array-length check and an index access in one And; nest the Ifs instead.
- For self-submitting forms use method="GET" or method="POST" to the same page and read Request.QueryString / Request.Form.`);

// ========== Assemble ==========
let combined = '';
for (let i = 0; i < sections.length; i++) {
    combined += `\n--- Section ${i + 1} ---\n${sections[i]}\n`;
}

if (combined.length > MAX_CHARS) {
    console.error(`WARNING: RAG content is ${combined.length.toLocaleString()} chars (max ${MAX_CHARS.toLocaleString()}).`);
}

const header = `// rag-data.js — Auto-generated by build-rag.js
// ASPPY Expert knowledge: simple single-file ASP pages + Bootstrap (~${Math.ceil(combined.length/1024)}KB).
// Re-run: node build-rag.js
// Generated: ${new Date().toISOString()}
`;

// JSON.stringify produces a valid, fully-escaped double-quoted JS string
// literal (handles quotes, backslashes, newlines, and — crucially — the
// single quotes that appear in VBScript comments). Use it directly rather
// than re-wrapping in single quotes, which would break on any apostrophe.
const jsString = JSON.stringify(combined);
const output = `${header}\nwindow.RAG_DATA = ${jsString};\n`;

fs.writeFileSync(OUTPUT, output, 'utf-8');

const totalChars = combined.length;
const estTokens = Math.ceil(totalChars / 4);
console.log(`rag-data.js generated:`);
console.log(`  Sections: ${sections.length}`);
console.log(`  Characters: ${totalChars.toLocaleString()}`);
console.log(`  Estimated tokens: ~${estTokens.toLocaleString()}`);
if (totalChars <= MAX_CHARS) {
    console.log(`  Within budget: ${((1 - totalChars/MAX_CHARS) * 100).toFixed(1)}% remaining`);
} else {
    console.log(`  OVER BUDGET by ${(totalChars - MAX_CHARS).toLocaleString()} chars`);
}
